name: Cross-Repository Automation

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Execute Python Script
        run: |
          python my.py    


      - name: Run Cross-Repository Task
        run: |
          git clone https://github.com/RahulRawatdevops/node-todo-cicd.git
          cd node-todo-cicd
     
